### ISSUE TITLE
Why does creating the config struct return an error

### ISSUE THREAD

**Issue by tian000** [launchdarkly/go-options#20]
The code generated by this returns the config struct or an error, but there can never be an error because all the generated `apply` methods return nil for their error.

**Comment by ashanbrown** [comment]
The standard generated apply methods do not return an error.  However, it's written this way so that a custom apply method could return an error without changing the interface.  I suppose we could provide an option to not return an error if you're confident that you'll never want to customize it in a way that would return an error.  Would that be useful to you?

**Comment by tian000** [comment]
Yes! That would be useful. I can put up a PR if you'd like.

**Comment by ashanbrown** [comment]
Sure, sounds good.

**Comment by tian000** [comment]
Here's the PR https://github.com/launchdarkly/go-options/pull/21
